echo "以下是12个项目的SQL插入语句："

echo "1. MegaTTS3项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'MegaTTS3项目',"
echo "'https://github.com/bytedance/MegaTTS3',"
echo "'Apache 2.0',"
echo "'https://huggingface.co/ByteDance/MegaTTS3',"
echo "'MIT',"
echo "'',"
echo "'🚀Lightweight and Efficient: The backbone of the TTS Diffusion Transformer has only 0.45B parameters. 🎧Ultra High-Quality Voice Cloning: You can try our model at Huggingface Demo🎉. The .wav and .npy files can be found at link1. Submit a sample on link2 to receive .npy voice latents you can use locally. 🌍Bilingual Support: Supports both Chinese and English, and code-switching. ✍️Controllable: Supports accent intensity control ✅ and fine-grained pronunciation/duration adjustment (coming soon).',"
echo "'For security issues, we do not upload the parameters of WaveVAE encoder to the above links. You can only use the pre-extracted latents from link1 for inference. If you want to synthesize speech for speaker A, you need \"A.wav\" and \"A.npy\" in the same directory. If you have any questions or suggestions for our model, please email us. This project is primarily intended for academic purposes. For academic datasets requiring evaluation, you may upload them to the voice request queue in link2 (within 24s for each clip). After verifying that your uploaded voices are free from safety issues, we will upload their latent files to link1 as soon as possible. In the coming days, we will also prepare and release the latent representations for some common TTS benchmarks.',"
echo "'测试环境字节服务器29.52.102.134',"
echo "'该项目为命令行工具，可以调命令，要求输入现有声音文件（wav文件），现有声音的资源文件（npy文件），新语音文本，运行后，可以生成新的声音文件（wav文件）',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "2. Wan2.1项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'Wan2.1项目',"
echo "'https://github.com/Wan-Video/Wan2.1',"
echo "'Apache 2.0',"
echo "'https://huggingface.co/Wan-AI/Wan2.1-T2V-14B,https://huggingface.co/Wan-AI/Wan2.1-T2V-1.3B',"
echo "'Apache 2.0',"
echo "'该项目有4个模型，目前试用了其中两个14B和1.3B',"
echo "'In this repository, we present Wan2.1, a comprehensive and open suite of video foundation models that pushes the boundaries of video generation. Wan2.1 offers these key features: 👍 SOTA Performance: Wan2.1 consistently outperforms existing open-source models and state-of-the-art commercial solutions across multiple benchmarks. 👍 Supports Consumer-grade GPUs: The T2V-1.3B model requires only 8.19 GB VRAM, making it compatible with almost all consumer-grade GPUs. It can generate a 5-second 480P video on an RTX 4090 in about 4 minutes (without optimization techniques like quantization). Its performance is even comparable to some closed-source models. 👍 Multiple Tasks: Wan2.1 excels in Text-to-Video, Image-to-Video, Video Editing, Text-to-Image, and Video-to-Audio, advancing the field of video generation. 👍 Visual Text Generation: Wan2.1 is the first video model capable of generating both Chinese and English text, featuring robust text generation that enhances its practical applications. 👍 Powerful Video VAE: Wan-VAE delivers exceptional efficiency and performance, encoding and decoding 1080P videos of any length while preserving temporal information, making it an ideal foundation for video and image generation.',"
echo "'无明确限制，但运行中发现GPU资源使用较高，运行时间较长，生成视频内容不可控，视频没有声音，后期对口形比较麻烦。',"
echo "'行外主机',"
echo "'该项目为命令行工具，可以调命令，支持输入描述文本生成5秒的视频，或输入描述文本生成图片。',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "3. Sonic项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'Sonic项目',"
echo "'https://github.com/jixiaozhong/Sonic',"
echo "'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International',"
echo "'https://huggingface.co/LeonJoe13/Sonic,https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt,https://huggingface.co/openai/whisper-tiny',"
echo "'不明确,不明确,Apache2.0',"
echo "'',"
echo "'Sonic: Shifting Focus to Global Audio Perception in Portrait Animation, CVPR 2025.',"
echo "'因license不可商用，无法引入',"
echo "'行外主机部署',"
echo "'该项目为命令行工具，可以调命令，要求输入现有声音文件（wav文件），现有人脸图片，运行后，可以生成自动对口形的新视频文件(mp4)',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "4. SparkTTS项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'SparkTTS项目',"
echo "'https://github.com/SparkAudio/Spark-TTS',"
echo "'Apache 2.0',"
echo "'https://huggingface.co/SparkAudio/Spark-TTS-0.5B',"
echo "'Creative Commons Attribution Non Commercial Share Alike 4.0',"
echo "'',"
echo "'Overview Spark-TTS is an advanced text-to-speech system that uses the power of large language models (LLM) for highly accurate and natural-sounding voice synthesis. It is designed to be efficient, flexible, and powerful for both research and production use. Key Features Simplicity and Efficiency: Built entirely on Qwen2.5, Spark-TTS eliminates the need for additional generation models like flow matching. Instead of relying on separate models to generate acoustic features, it directly reconstructs audio from the code predicted by the LLM. This approach streamlines the process, improving efficiency and reducing complexity. High-Quality Voice Cloning: Supports zero-shot voice cloning, which means it can replicate a speaker's voice even without specific training data for that voice. This is ideal for cross-lingual and code-switching scenarios, allowing for seamless transitions between languages and voices without requiring separate training for each one. Bilingual Support: Supports both Chinese and English, and is capable of zero-shot voice cloning for cross-lingual and code-switching scenarios, enabling the model to synthesize speech in multiple languages with high naturalness and accuracy. Controllable Speech Generation: Supports creating virtual speakers by adjusting parameters such as gender, pitch, and speaking rate.',"
echo "'因模型license不可商用，所以不能引入',"
echo "'测试环境字节服务器29.52.102.134',"
echo "'该项目为命令行工具，可以调命令，也有一个简易UI，通过输入现有声音+现有声音对应文字+新文字，合成新的语音',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "5. HeyGem.AI项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'HeyGem.AI项目',"
echo "'https://github.com/GuijiAI/HeyGem.ai',"
echo "'Silicon Intelligence COMMUNITY LICENSE AGREEMENT',"
echo "'',"
echo "'Heygem digital human clone agents and plugins have been successfully launched on the Coze platform. No complex deployment is required, even novice users can easily get started and use it directly. The usage guide is as follows: Step 1: Go to https://guiji.cn/open-platform to claim free digital human clone rights (claim address: https://app.guiji.cn/platform); Step 2: Move to the Coze platform and fully experience the silicon-based intelligent digital human agent to generate broadcast videos (experience address: https://www.coze.cn/store/agent/7488696243959431206); What are you waiting for? Come and generate unique digital human broadcast videos with one click!',"
echo "'该license与杜胜了解，为高风险license，不建议引入',"
echo "'部署中发现该项目基于Windows，需要100G以上硬盘，及较大GPU，因无合适主机，无法进行部署。',"
echo "'未能成功运行',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "6. DCT-NET项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, project_description, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'DCT-NET项目',"
echo "'https://github.com/menyifang/DCT-Net',"
echo "'Apache 2.0',"
echo "'https://modelscope.cn/models/iic/cv_unet_person-image-cartoon_compound-models',"
echo "'Apache 2.0',"
echo "'DCT-Net: Domain-Calibrated Translation for Portrait Stylization Project page | Video | Paper Official implementation of DCT-Net for Full-body Portrait Stylization. DCT-Net: Domain-Calibrated Translation for Portrait Stylization, Yifang Men1, Yuan Yao1, Miaomiao Cui1, Zhouhui Lian2, Xuansong Xie1, 1DAMO Academy, Alibaba Group, Beijing, China 2Wangxuan Institute of Computer Technology, Peking University, China In: SIGGRAPH 2022 (TOG) arXiv preprint',"
echo "'行外主机部署成功',"
echo "'该项目为命令行工具，可以调命令，输入一张图片，生成7种不同的卡通图片',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "7. DH-LIVE项目:"
echo "INSERT INTO open_source_project (project_name, project_url, model_url, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'DH-LIVE项目',"
echo "'https://github.com/kleinlee/DH_live',"
echo "'https://drive.google.com/drive/folders/1az5WEWOFmh0_yrF3I9DEyctMyjPolo8V?usp=sharing',"
echo "'',"
echo "'Mobile and Web Real-time Live Streaming Digital Human! 实时数字人 全网最快 Notes：目前项目主要维护DH_live_mini, 目前最快的数字人方案，没有之一，项目含有网页推理的案例，不依赖任何GPU，可在任何手机设备实时运行。原版DH_live已不再获支持，希望慎重考虑使用。原版使用方法参见here。 DHLive_mini手机浏览器直接推理bilibili video',"
echo "'因license不明确，无法引入',"
echo "'外部主机部署成功',"
echo "'该项目为一简易前端， 通过上传一段视频，提取面部特征，生成一个加密文件，然后在网页端，显示一个聊天头像，该头像口型可变化。',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "8. Parker-TTS项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, model_license, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'Parker-TTS项目',"
echo "'https://github.com/huggingface/parler-tts',"
echo "'Apache2.0',"
echo "'https://huggingface.co/parler-tts/parler_tts_mini_v0.1',"
echo "'Apache2.0',"
echo "'Parler-TTS is a lightweight text-to-speech (TTS) model that can generate high-quality, natural sounding speech in the style of a given speaker (gender, pitch, speaking style, etc). It is a reproduction of work from the paper Natural language guidance of high-fidelity text-to-speech with synthetic annotations by Dan Lyth and Simon King, from Stability AI and Edinburgh University respectively. Contrarily to other TTS models, Parler-TTS is a fully open-source release. All of the datasets, pre-processing, training code and weights are released publicly under permissive license, enabling the community to build on our work and develop their own powerful TTS models. This repository contains the inference and training code for Parler-TTS. It is designed to accompany the Data-Speech repository for dataset annotation.',"
echo "'不支持中文合成，英文合成效果较差',"
echo "'外部主机部署成功',"
echo "'通过命令行，输入一段文字，可生成语音文件',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "9. MuseTalk项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, model_url, description, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'MuseTalk项目',"
echo "'https://github.com/TMElyralab/MuseTalk',"
echo "'MIT',"
echo "'https://huggingface.co/TMElyralab/MuseTalk,https://huggingface.co/stabilityai/sd-vae-ft-mse/tree/main,https://huggingface.co/yzd-v/DWPose/tree/main,https://drive.google.com/file/d/154JgKpzCPW82qINcVieuPH3fZ2e0P812/view',"
echo "'',"
echo "'MuseTalk: Real-Time High-Fidelity Video Dubbing via Spatio-Temporal Sampling Yue Zhang*, Zhizhou Zhong*, Minhao Liu*, Zhaokang Chen, Bin Wu†, Yubin Zeng, Chao Zhan, Junxin Huang, Yingjie He, Wenjiang Zhou (*Equal Contribution, †Corresponding Author, benbinwu@tencent.com) Lyra Lab, Tencent Music Entertainment github huggingface space Technical report We introduce MuseTalk, a real-time high quality lip-syncing model (30fps+ on an NVIDIA Tesla V100). MuseTalk can be applied with input videos, e.g., generated by MuseV, as a complete virtual human solution.',"
echo "'多个模型license不明确，无法引入',"
echo "'外部主机部署成功',"
echo "'通过修改源代码，实现了调命令生成视频，通过输入一段现有视频+声音文件，可产生新的视频，现在视频要求已有各种动作。',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"

echo ""
echo "10. DeepSearcher项目:"
echo "INSERT INTO open_source_project (project_name, project_url, project_license, project_description, project_limitations, deployment_status, operation_status, created_by, updated_by, is_delete) VALUES ("
echo "'DeepSearcher项目',"
echo "'https://github.com/zilliztech/deep-searcher',"
echo "'Apache 2.0',"
echo "'DeepSearcher combines cutting-edge LLMs (OpenAI o1, o3-mini, DeepSeek, Grok 3, Claude 3.7 Sonnet, Llama 4, QwQ, etc.) and Vector Databases (Milvus, Zilliz Cloud etc.) to perform search, evaluation, and reasoning based on private data, providing highly accurate answer and comprehensive report. This project is suitable for enterprise knowledge management, intelligent Q&A systems, and information retrieval scenarios.',"
echo "'目前加载中文PDF会失败',"
echo "'行内字节主机部署成功',"
echo "'通过修改源代码，实现了基本的命令行调用，可对PDF文件进行提问',"
echo "'DINGHAIJIANG',"
echo "'DINGHAIJIANG',"
echo "0);"
